# Generated by Django 4.2.5 on 2024-05-08 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD1app', '0002_usuario_tipos'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo_e',
            name='tipos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CRUD1app.tipo_e', unique=True),
        ),
    ]
